# Generated by Django 3.2 on 2021-11-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
