# Generated by Django 3.2 on 2021-11-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_auto_20211109_2221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_supplier",
            field=models.BooleanField(default=False, verbose_name="supplier"),
        ),
    ]
