from django.urls import path
from rest_framework.decorators import permission_classes, authentication_classes
from rest_framework.permissions import AllowAny
from market.permissions.permission import ROLE_USER, ROLE_ADMIN, UserPermissionsObj
from market.authentication import SafeJWTAuthentication
from market.views import (
    CategoryViews,
    ProductViews,
    UserViews,
    GroupViews,
    CommentsViews,
    CartItemsViews,
    OrdersViews,
)

urlpatterns = [
    # USERS
    path(
        "user/access_token/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([AllowAny])(UserViews.AccessToken)
        ).as_view(),
    ),
    path(
        "user/refresh_token/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([UserPermissionsObj])(UserViews.RefreshToken)
        ).as_view(),
    ),
    path(
        "user/registration/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([AllowAny])(UserViews.UserRegistrationView)
        ).as_view(),
    ),
    path(
        "user/create_super_user/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([AllowAny])(UserViews.CreateSuperUserView)
        ).as_view(),
    ),
    path(
        "user/delete_user_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([UserPermissionsObj])(UserViews.DeleteUserByIdView)
        ).as_view(),
    ),
    path(
        "user/delete_all_users/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_ADMIN])(UserViews.DeleteAllUsersView)
        ).as_view(),
    ),
    path(
        "user/update_user_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([UserPermissionsObj])(UserViews.UpdateUserView)
        ).as_view(),
    ),
    path(
        "user/find_all_users/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([UserPermissionsObj])(UserViews.GetUserView)
        ).as_view(),
    ),
    path(
        "user/find_user_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([UserPermissionsObj])(UserViews.FindUserByIdView)
        ).as_view(),
    ),
    # GROUPS
    path(
        "group/create_group/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([AllowAny])(GroupViews.CreateGroupView)
        ).as_view(),
    ),
    path(
        "group/delete_group_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_ADMIN])(GroupViews.DeleteGroupByIdView)
        ).as_view(),
    ),
    path(
        "group/update_group_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_ADMIN])(GroupViews.UpdateGroupByIdView)
        ).as_view(),
    ),
    path(
        "group/find_all_groups/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_ADMIN])(GroupViews.GetGroupView)
        ).as_view(),
    ),
    path(
        "group/find_group_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_ADMIN])(GroupViews.FindGroupByIdView)
        ).as_view(),
    ),
    # CATEGORIES
    path(
        "category/create_category/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CategoryViews.CreateCategoryView)
        ).as_view(),
    ),
    path(
        "category/delete_category_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CategoryViews.DeleteCategoryByIdView)
        ).as_view(),
    ),
    path(
        "category/update_category_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CategoryViews.UpdateCategoryByIdView)
        ).as_view(),
    ),
    path(
        "category/find_all_categories/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CategoryViews.GetCategoryView)
        ).as_view(),
    ),
    path(
        "category/find_category_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CategoryViews.FindCategoryByIdView)
        ).as_view(),
    ),
    # PRODUCTS
    path(
        "product/create_product/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(ProductViews.CreateProductView)
        ).as_view(),
    ),
    path(
        "product/delete_product_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(ProductViews.DeleteProductByIdView)
        ).as_view(),
    ),
    path(
        "product/delete_all_products/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(ProductViews.DeleteAllProductView)
        ).as_view(),
    ),
    path(
        "product/update_product_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(ProductViews.UpdateProductByIdView)
        ).as_view(),
    ),
    path(
        "product/find_all_products/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(ProductViews.GetProductView)
        ).as_view(),
    ),
    path(
        "product/find_product_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(ProductViews.FindProductByIdView)
        ).as_view(),
    ),
    # COMMENTS
    path(
        "comments/create_comment/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([UserPermissionsObj])(CommentsViews.CreateCommentView)
        ).as_view(),
    ),
    path(
        "comments/create_replies/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CommentsViews.CreateRepliesView)
        ).as_view(),
    ),
    path(
        "comments/delete_comment_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CommentsViews.DeleteCommentByIdView)
        ).as_view(),
    ),
    path(
        "comments/update_comment_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CommentsViews.UpdateCommentByIdView)
        ).as_view(),
    ),
    path(
        "comments/find_all_comments/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([UserPermissionsObj])(CommentsViews.GetCommentView)
        ).as_view(),
    ),
    path(
        "comments/find_comment_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([UserPermissionsObj])(CommentsViews.FindCommentByIdView)
        ).as_view(),
    ),
    # CARTITEMS
    path(
        "cartitem/create_cartitem/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CartItemsViews.CreateCartItemsView)
        ).as_view(),
    ),
    path(
        "cartitem/delete_cartitem_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CartItemsViews.DeleteCartItemsByIdView)
        ).as_view(),
    ),
    path(
        "cartitem/update_cartitem_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CartItemsViews.UpdateCartItemsByIdView)
        ).as_view(),
    ),
    path(
        "cartitem/find_all_cartitems/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CartItemsViews.GetCartItemsView)
        ).as_view(),
    ),
    path(
        "cartitem/find_cartitem_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(CartItemsViews.FindCartItemsByIdView)
        ).as_view(),
    ),
    # ORDERS
    path(
        "order/create_order/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(OrdersViews.CreateOrderView)
        ).as_view(),
    ),
    path(
        "order/delete_order_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(OrdersViews.DeleteOrderByIdView)
        ).as_view(),
    ),
    path(
        "order/delete_all_orders/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(OrdersViews.DeleteAllOrdersView)
        ).as_view(),
    ),
    path(
        "order/find_all_orders/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(OrdersViews.GetOrdersView)
        ).as_view(),
    ),
    path(
        "order/find_order_by_id/<int:pk>/",
        authentication_classes([SafeJWTAuthentication])(
            permission_classes([ROLE_USER])(OrdersViews.FindOrderByIdView)
        ).as_view(),
    ),
]
